### ISSUE TITLE
Improve WIKI and README

### ISSUE THREAD

**Issue by developerCodex** [developerCodex/musicbot#16]
If anyone is good with editing and making good wiki and details and writing please comment below, we will be needing someoen who can improve and make the wiki and the readme professional.

**Comment by developerCodex** [comment]
This will be getting done by next Friday, or so. Please stay updated.

**Comment by developerCodex** [comment]
The wiki, still needs to be kinda updated and the readme needs to be professional @JoeBanks13 please let's do this.

**Comment by developerCodex** [comment]
The wiki has been updated quite a bit. We're done with updating the wiki until a huge update that changes a lot of things comes out. But we just may need some more professionalism in the readme.

**Comment by JoeBanks13** [comment]
OY OY SAVALOY






^ Dat professional enough? 😂

**Comment by developerCodex** [comment]
The READme is too professional we cannot make it anymore professional.
