### ISSUE TITLE
OYOY DEV WE NEED TO UPDATE THE COMMANDS IN THE WIKI

### ISSUE THREAD

**Issue by JoeBanks13** [developerCodex/musicbot#22]
Dear Mr DevCodex,

We seem to be out of date in the commands on the [Wiki](https://github.com/developerCodex/musicbot/wiki/Commands).

We need to add the new commands i.e. remindme, lalala.

Thank you for your time,

Mr J Banks

Managing Director
DeveloperCodex MusicBot
555-444-NU-PHONE

**Comment by developerCodex** [comment]
Yep, we will be doing that.

**Comment by JoeBanks13** [comment]
Done it

**Comment by developerCodex** [comment]
Thank you.

**Comment by developerCodex** [comment]
This issue is now resloved and will be closed.
