### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by TishGitHub** [developerCodex/musicbot#25]
![image](https://cloud.githubusercontent.com/assets/22654782/20454972/8a15d8f2-ae71-11e6-805f-2351221e4e44.png)
I get bot.on is not function

**Comment by developerCodex** [comment]
Are you sure you've installed it correctly and read the installation? The bot is discord.js v8

**Comment by JoeBanks13** [comment]
Hey there, we upgraded the bot to newer discord.js and think this is a better repo: http://github.com/JoeBanks13/Music-Butt

**Comment by developerCodex** [comment]
@JoeBanks13 And I've got no credit.

**Comment by developerCodex** [comment]
This ticket has been closed as it is resolved.

**Comment by JoeBanks13** [comment]
@developerCodex That wasn't me, if you look at the commits @asianboiFRC was the one who made a commit named `Removed developerCodex references`, #itsuxtobeyou

**Comment by developerCodex** [comment]
@JoeBanks13 I told you to tell him to give me credit for it.
