### ISSUE TITLE
Make the wiki better

### ISSUE THREAD

**Issue by asianboiFRC** [developerCodex/musicbot#3]
So I see the wiki is not very well edited - @developerCodex make me a contributor so I can edit the wiki and make the wiki auto-update when you make new commands

**Comment by developerCodex** [comment]
I will see about this, just let me get everything organized right now.

**Comment by developerCodex** [comment]
@asianboiFRC How, are you gonna make the wiki auto-update?

**Comment by asianboiFRC** [comment]
@developerCodex I'll make a help.txt for the help function to return, and have the wiki pull from it too.

**Comment by developerCodex** [comment]
I am just trying to get some cool formats right now, but I will consider it and let me make sure @JoeBanks13 is okay with it.

**Comment by developerCodex** [comment]
We are aware that the wiki is a bit buggy, and that it needs improvement with the homepage and the installation. 

We should be able to fix this and edit it, and use professionalism in the wiki and the read me, so lots of changes will be going on. This conversation may be locked.

**Comment by developerCodex** [comment]
Where hoping to make a front cover for the GitHub page, and the wiki, I believe if I am correct.

**Comment by developerCodex** [comment]
I have unlocked the conversation, the front cover for the GitHub readme will be sweat, and it's coming out shortly. Stay posted! We're also getting a tons of things done tmrrw. 

Check back later.

**Comment by developerCodex** [comment]
The wiki has gotten better on the installation page, the home page will be also getting better.
